# enable ES6

parser: babel-eslint

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true # enable React's JSX
  allowImportExportEverywhere: false
  codeFrame: true


# register plugins
plugins:
  - meteor
  - react

# use the rules of eslint-config-airbnb
# and the recommended rules of eslint-plugin-meteor
extends:
  - airbnb/base
  - plugin:meteor/recommended
  - plugin:react/recommended

# registerenvironments
env:
  meteor: true
  browser: true
  node: true
  
  

rules:
  # overwrite some rules  
  semi: 'error'
  no-unexpected-multiline: 2
  object-curly-newline: 0
  no-throw-literal: 0
  no-underscore-dangle: 0
  import/no-named-as-default: 0
  no-nested-ternary: 0
  arrow-parens: 0
  class-methods-use-this: 0
  max-len: 0
  # eslint-plugin-meteor
  meteor/no-session: [0] # allow Session
  meteor/prefer-session-equals: [0] # prefer Session.equals instead
  import/no-extraneous-dependencies: off
  react/require-extension: off
  import/extensions:
    - off
    - never
  import/prefer-default-export: ['off']
  react/jsx-uses-vars: 1
  consistent-return: off #turn off the function return type error
  one-var: [error, never]
  rules: {
    class-methods-use-this: [2, {
      exceptMethods: [
        render,
        getInitialState,
        getDefaultProps,
        getChildContext,
        componentWillMount,
        componentDidMount,
        componentWillReceiveProps,
        shouldComponentUpdate,
        componentWillUpdate,
        componentDidUpdate,
        componentWillUnmount,
      ],
    }],
  }
  no-unused-expressions: ["error", { allowShortCircuit: true, allowTernary: true }]

globals:
  # collections
  describe: false
  beforeEach: false
  fs: false
  FS: false
  Materialize: false
  Roles: false
  exportcsv: false
  require: false
  expect: false
  test: false
  it: false

  # packages
  FlowRouter: false 
  moment: false 
  Picker: false
settings:
  import/core-modules: [meteor/meteor]
  import/resolver: meteor
  react: 
    version: "detect"
